steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID", "."]
- name: gcr.io/cloud-builders/docker
  args: ['tag',
    'gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID',
    'gcr.io/$PROJECT_ID/$REPO_NAME:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:latest"]
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     gcloud components install kubectl
#     gsutil cp gs://kube-key/kubeconfig .
#     export KUBECONFIG=kubeconfig
#     kubectl set image daemonset/torrent-web-cache --namespace=webtor torrent-web-cache=rg.fr-par.scw.cloud/webtor/$REPO_NAME:$REVISION_ID || exit 0